#!/bin/bash -xe
. ./hooks/env  # (1)
docker build \  # (2)
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg "SOURCE_COMMIT=$GIT_SHA1" \
    --build-arg "DOCKERFILE_PATH=$DOCKERFILE_PATH" \
    --build-arg "SOURCE_TYPE=$SOURCE_TYPE" \
    --build-arg "NODE_TOOL_FLAGS=--max-old-space-size=4096" \
    ${VERSION:+--build-arg "VERSION=$VERSION"} \  # (3)
    -t $IMAGE_NAME ..  # (4)
