export const parentTags = [
  {
    displayTitle: "Featured",
    name: "Featured",
    slug: "featured",
    subTags: [
      { slug: "ring-set" },
      { slug: "gifts-under-150" },
      { slug: "engagement-wedding-rings-collection" },
      { slug: "minimal-rings" },
      { slug: "statement" },
      { slug: "stacking" },
      { slug: "under-75" },
      { slug: "stud" },
      { slug: "hoops" },
      { slug: "climber" },
      { slug: "huggie" },
      { slug: "under-100" },
      { slug: "personalized-jewelry" },
      { slug: "choker" },
      { slug: "pendant" },
      { slug: "layered" },
      { slug: "bestsellers" },
      { slug: "last-chance" }
    ]
  },
  {
    displayTitle: "Category",
    name: "Category",
    slug: "category",
    subTags: [
      { slug: "rings" },
      { slug: "earrings" },
      { slug: "necklaces" },
      { slug: "bracelets" },
      { slug: "anklets" }
    ]
  },
  {
    displayTitle: "Type",
    name: "Type",
    slug: "type",
    subTags: [
      { slug: "solid-gold" },
      { slug: "vermeil-plated" },
      { slug: "other-type" }
    ]
  },
  {
    displayTitle: "Metal Tone",
    name: "Metal Tone",
    slug: "metal-tone",
    subTags: [
      { slug: "yellow-gold" },
      { slug: "rose-gold" },
      { slug: "white-gold" },
      { slug: "sterling-silver" },
      { slug: "brass" }
    ]
  },
  {
    displayTitle: "Designers",
    name: "Designers",
    slug: "designers",
    subTags: [
      { displayTitle: "A Peace Treaty" },
      { displayTitle: "A.M. Thorne" },
      { displayTitle: "Above Average Studio" },
      { displayTitle: "Aletheia & Phos" },
      { displayTitle: "Alex Mika" },
      { displayTitle: "Amarilo Jewelry" },
      { displayTitle: "Amber Sceats" },
      { displayTitle: "Artemer" },
      { displayTitle: "Bing Bang" },
      { displayTitle: "Bread & Circus" },
      { displayTitle: "Carrie Elizabeth Jewelry" },
      { displayTitle: "Carried Jewels" },
      { displayTitle: "Casa Clara" },
      { displayTitle: "Charlie and Marcelle" },
      { displayTitle: "Cities in Dust" },
      { displayTitle: "Claflin, Thayer & Co" },
      { displayTitle: "Cloverpost" },
      { displayTitle: "Curious Creatures" },
      { displayTitle: "Dea Dia" },
      { displayTitle: "Delusions of Grandeur" },
      { displayTitle: "Elizabeth Stone" },
      { displayTitle: "Emi Conner" },
      { displayTitle: "Emily Amey Jewelry" },
      { displayTitle: "Ettika" },
      { displayTitle: "Euclide" },
      { displayTitle: "Everett" },
      { displayTitle: "Eyland" },
      { displayTitle: "Five and Two" },
      { displayTitle: "Gage Huntley" },
      { displayTitle: "Girls Crew" },
      { displayTitle: "Gjenmi Jewelry" },
      { displayTitle: "I Like it Here Club" },
      { displayTitle: "James and Irisa" },
      { displayTitle: "Joy Dravecky" },
      { displayTitle: "Kamaria" },
      { displayTitle: "Kate + Mari" },
      { displayTitle: "Keltie Leanne Designs" },
      { displayTitle: "La Kaiser" },
      { displayTitle: "Laura Lombardi" },
      { displayTitle: "Laurie Fleming Jewelry" },
      { displayTitle: "Leah Alexandra" },
      { displayTitle: "Liesel Love" },
      { displayTitle: "Lover's Tempo" },
      { displayTitle: "Luiny" },
      { displayTitle: "Lulu Frost" },
      { displayTitle: "Luminosity" },
      { displayTitle: "LUMO" },
      { displayTitle: "Lust & Luster" },
      { displayTitle: "Machete Jewelry" },
      { displayTitle: "Marva Atelier" },
      { displayTitle: "Mason Grace Jewelry" },
      { displayTitle: "Melanie Auld" },
      { displayTitle: "Melanie Casey" },
      { displayTitle: "Melinda Maria" },
      { displayTitle: "Merewif" },
      { displayTitle: "Minette" },
      { displayTitle: "MinimalVS" },
      { displayTitle: "Minoux" },
      { displayTitle: "MOYA" },
      { displayTitle: "Nectar Nectar" },
      { displayTitle: "Nicha Jewelry" },
      { displayTitle: "Nora Sermez" },
      { displayTitle: "Paradiiso" },
      { displayTitle: "Point No Point Studio" },
      { displayTitle: "Reliquia" },
      { displayTitle: "Robin Haley Jewelry" },
      { displayTitle: "Shashi" },
      { displayTitle: "Slate and Stone" },
      { displayTitle: "Sofia Zakia" },
      { displayTitle: "Sophie Monet Jewelry" },
      { displayTitle: "Sundara Mar" },
      { displayTitle: "Susan Alexandra" },
      { displayTitle: "Tai Jewelry" },
      { displayTitle: "Temple of the Sun" },
      { displayTitle: "Tippy Taste Jewelry" },
      { displayTitle: "Vayü" },
      { displayTitle: "Wolf Circus" },
      { displayTitle: "Yunis K" },
      { displayTitle: "Zahava" }
    ]
  },
  {
    displayTitle: "Stone",
    name: "Stone",
    slug: "stone",
    subTags: [
      { slug: "abalone" },
      { slug: "acetate" },
      { slug: "amethyst" },
      { slug: "aquamarine" },
      { slug: "chalcedony" },
      { slug: "citrine" },
      { slug: "coral" },
      { slug: "cz" },
      { slug: "diamond" },
      { slug: "druzy" },
      { slug: "emerald" },
      { slug: "enamel" },
      { slug: "galena" },
      { slug: "garnet" },
      { slug: "gemstone" },
      { slug: "glass" },
      { slug: "jade" },
      { slug: "labradorite" },
      { slug: "malachite" },
      { slug: "moodstone" },
      { slug: "moonstone" },
      { slug: "morganite" },
      { slug: "onyx" },
      { slug: "opal" },
      { slug: "pearl" },
      { slug: "peridot" },
      { slug: "pyrite" },
      { slug: "quartz" },
      { slug: "ruby" },
      { slug: "sapphire" },
      { slug: "sunstone" },
      { slug: "swarovski" },
      { slug: "tanzanite" },
      { slug: "topaz" },
      { slug: "tourmaline" },
      { slug: "turquoise" }
    ]
  },
  {
    displayTitle: "Banners",
    name: "banner",
    slug: "banner",
    regex: /^__[\w\s.-]+/
  }
];
